name: ''
description: ''
author:
  - Will Dampier
input:

  - jaspar : Description
output:

  - heatmap : Description
params:

  - dpi : Description
  - name_filter : Description
  - cmap : Description