name: dorado demux
description: Wrapper for running dorado demultiplexing
authors:
  - Will Dampier, PhD
input:
  - reads file or directory (any HTS format)
output:
  - output directory for demultiplexed reads
params:
  - kit_name: barcoding kit name (required unless no_classify is True)
  - no_classify: skip barcode classification (optional)
  - sample_sheet: path to sample sheet (optional)
  - max_reads: maximum number of reads to process (optional)
  - read_ids: file with newline-delimited list of reads to demux (optional)
  - emit_fastq: output in fastq format instead of BAM (optional)
  - emit_summary: emit summary file (optional)
  - barcode_both_ends: require both ends to be barcoded (optional)
  - no_trim: skip barcode trimming (optional)
  - sort_bam: sort BAM output files (optional, requires no_trim)
  - barcode_arrangement: path to custom barcode arrangement file (optional)
  - barcode_sequences: path to custom barcode sequences file (optional)
  - dorado_path: path to dorado binary (optional, defaults to 'dorado')
notes: |
  * The wrapper runs dorado demux to perform barcode demultiplexing
  * Input can be a single file or a directory (recursive mode auto-enabled for directories)
  * Either kit_name or no_classify must be specified
  * Requires dorado to be installed and available in PATH (unless dorado_path is specified)
  * Number of threads can be controlled via snakemake threads directive
  * stderr is redirected to the snakemake log if specified
  * sort_bam option requires no_trim to be True 