channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - biopython
  - pysam
  - pandas
  - numpy=1.24.3
  - pyyaml
  - pillow
  - pip
  - pip:
    - transformers>=4.36.0
    - sentencepiece
    - protobuf