channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pysam
  - biopython
  - pandas
  - pillow
  - numpy
  - pyyaml
  - pip
  - pytorch=1.12.1
  - cudatoolkit=11.6
  - pip:
    - transformers>=4.36.0
    - sentencepiece
    - protobuf 