from os.path import join

# Create test output directory
import os
os.makedirs("test_output", exist_ok=True)

rule all:
    input:
        "test_output/basic.fasta",
        "test_output/frame1.fasta",
    conda: "env.yaml"
    shell: "pytest tests.py"

# Test with basic parameters
rule test_basic:
    input:
        "test_data.fasta"
    output:
        "test_output/basic.fasta"
    params:
        frame=0,
        table=1,
        stop_symbol="*",
        to_stop=False,
        cds=False
    log:
        "test_output/basic.log"
    wrapper:
        "file:../"

# Test with frame 1
rule test_frame1:
    input:
        "test_data.fasta"
    output:
        "test_output/frame1.fasta"
    params:
        frame=1,
        table=1,
        stop_symbol="*",
        to_stop=False,
        cds=False
    log:
        "test_output/frame1.log"
    wrapper:
        "file:../"
