use-conda: true
conda-prefix: /ifs/groups/wndGrp/conda_prefix
executor: slurm
latency-wait: 20
jobs: 20
cores: 1
config:
  DORADO_MODELS_DIR: /ifs/groups/wndGrp/conda_envs/damlab-wrappers/dorado_models
default-resources:
  slurm_account: wndprj
  slurm_partition: 'def'
  runtime: 15
  
