name: bam2gel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas
  - seaborn
  - matplotlib
  - numpy
  - pyyaml
  - pysam 
  - pip
  - pip:
    - git+https://github.com/DamLabResources/cigarmath.git@main