name: dorado aligner
description: Wrapper for running dorado aligner
authors:
  - Will Dampier, PhD
input:
  - index: minimap2 index file
  - calls: basecalled reads (BAM format)
output:
  - aligned BAM file
params:
  - k: minimap2 k-mer size (max 28)
  - w: minimap2 minimizer window size
  - I: minimap2 index batch size
  - N: max number of secondary alignments to retain
  - r: chaining/alignment bandwidth
  - x: minimap2 preset (default: "lr:hq")
  - secondary: output secondary alignments (boolean)
  - Y: use soft clipping for supplementary alignments (boolean)
  - junc_bed: gene annotations in BED12 format
  - mm2_opts: additional minimap2 options
  - dorado_path: path to dorado binary (optional)
  - recursive: search subfolders for input files (boolean)
  - output_dir: output directory for files
  - emit_summary: emit alignment summary file (boolean)
  - bed_file: bed file for overlap counting
  - max_reads: maximum number of reads to process
  - verbose: increase verbosity (boolean)
threads: number of threads for alignment (optional)
notes: |
  * Wrapper for dorado aligner tool
  * Uses minimap2 for alignment
  * All minimap2 parameters are optional
  * stderr is redirected to the snakemake log if specified 