name: strainline
description: Wrapper for running strainline haplotype reconstruction
authors:
  - Will Dampier, PhD
input:
  - reads in FASTQ format
output:
  - directory containing all results OR
  - FASTA file containing haplotype sequences
params:
  - prefix: installation prefix for strainline
  - platform: sequencing platform (pb or ont)
  - min_trimmed_len: minimum trimmed read length (optional)
  - topk: choose top k seed reads (optional)
  - min_ovlp_len: minimum read overlap length (optional)
  - min_identity: minimum identity of overlaps (optional)
  - min_seed_len: minimum seed read length (optional)
  - max_oh: maximum overhang length for overlaps (optional)
  - iter: number of iterations for contig extension (optional)
  - max_gd: maximum global divergence for merging haplotypes (optional)
  - max_ld: maximum local divergence for merging haplotypes (optional)
  - max_co: maximum overhang length for contig contains (optional)
  - min_abun: minimum abundance for filtering haplotypes (optional)
  - rm_misassembly: break contigs at potential misassembled positions (optional)
  - correct_err: perform error correction for input reads (optional)
  - dsim: alignment similarity percentage for Daligner (optional)
notes: |
  * The wrapper runs strainline for haplotype-aware assembly of long reads
  * Input must be in FASTA format
  * Output can be either a directory with all results or a single FASTA file with haplotypes
  * Requires strainline to be installed via the provided makefile
  * Number of threads can be controlled via snakemake threads directive
  * stderr is redirected to the snakemake log if specified 