name: strainline clipqs
description: Wrapper for clipping and orienting sequences using minimap2 alignment
authors:
  - Will Dampier, PhD
input:
  - sequences: FASTA file containing sequences to process
  - reference: Reference FASTA file for alignment
output:
  - Processed FASTA file with clipped and oriented sequences
params:
  - min_coverage: minimum alignment coverage (optional, default 0.8)
  - min_identity: minimum alignment identity (optional, default 0.8)
notes: |
  * Aligns input sequences to reference using minimap2
  * Orients sequences to match reference direction
  * Clips unaligned ends from sequences
  * Filters sequences based on coverage and identity thresholds
  * Outputs processed sequences in FASTA format 