name: ''
description: ''
author:
  - Will Dampier
input:
  - control : The trace file from the control sample
  - edited : The trace file from the edited sample
params:
  - target : The target sequence(s); comma seperated if multiple (required)
  - donor : The donor sequence if performing HDR.

output:
  - out : Directory for output files.